### ISSUE TITLE
Output size issue in alexnet and inception 

### ISSUE THREAD

**Issue by morawi** [creafz/pytorch-cnn-finetune#4]
AlexNet

  File "/lib/python3.6/site-packages/cnn_finetune/base.py", line 158, in calculate_classifier_in_features
    output = original_model.features(input_var)

File "/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 143, in forward
    self.return_indices)

  File "/lib/python3.6/site-packages/torch/nn/functional.py", line 334, in max_pool2d
    ret = torch._C._nn.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)

RuntimeError: Given input size: (256x1x1). Calculated output size: (256x0x0). Output size is too small at /opt/conda/conda-bld/pytorch_1518243271935/work/torch/lib/THNN/generic

inceptionresnetv2
  File "/lib/python3.6/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: Given input size: (320, 1, 1). Calculated output size: (100, 0, 0). Output size is too small.

inception_v3
 line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: Given input size: (288, 1, 1). Calculated output size: (100, 0, 0). Output size is too small.

inception_v4
Given input size: (384, 1, 1). Calculated output size: (100, 0, 0). Output size is too small.

NB1. For AlexNet, changing the train_original_classifier to True (it was False in all the above) gave the following error:
  File "/lib/python3.6/site-packages/cnn_finetune/contrib/torchvision.py", line 93, in check_args
    'For the original classifier '

Exception: For the original classifier input_size value must be (224, 224)

NB2. pre_trained_model = True in all the above

**Comment by creafz** [comment]
The problem is that some layers in a neural network (such as pooling layers or convolutions with stride > 1) reduce spatial dimensions of the activation map. So if the input image size is too small, you can't make a full forward pass through a network because activation map somewhere in the middle of the network will become too small.

One possible solution to this problem is to increase the size of the input image (for example you can rescale it or pad image borders with zeros).

I will try to make this exception less cryptic.

**Comment by creafz** [comment]
Now `make_model` will show a more clear exception message when the input_size value is too small for a selected model architecture.

For example `make_model('vgg16', num_classes=10, pretrained=True, input_size=(8,8))` will raise an exception with the following message: `RuntimeError: Input size (8, 8) is too small for this model. Try increasing the input size of images and change the value of input_size argument accordingly.`

**Comment by morawi** [comment]
But increasing the input size of images will increase the computational complexity. Any other way around this?

**Comment by creafz** [comment]
You can modify the architecture of the original model (for example remove some downsampling layers). However, this procedure can lower the quality of the model, because the model was trained using all the layers. If you want to modify the architecture you have to use the original model definition from torchvision or pretrainedmodels, since there are many ways of doing this task and maintaining them in pytorch-cnn-finetune will be a difficult problem to solve.

**Comment by morawi** [comment]
Thanks! It seems that for VGGs, the minimum acceptable size is 32x32. 
Not sure if there could be a warning somewhere in base.py, before the execution flow goes to Torch.
